name: build-docker
runs-on: ubuntu-latest
inputs:
  registry:
    description: 'registry to push to'
    required: true
  image_name:
    description: 'image name to push'
    required: true
  push:
    description: 'should we push the built image?'
    required: true
  github_token:
    description: 'token to publish'
    require: true
runs:
  using: composite
  shell: bash
  steps:
    - name: Log in to registry
      uses: docker/login-action@v3
      if: ${{ inputs.push == true }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - name: Extract metadata for docker
      id: meta
      uses: docker/metadata-action@v5
      if: ${{ inputs.push == true }}
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
    - name: Build and maybe push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.output.labels }}
