version: '3'

includes:
  go: .taskfiles/go.yaml
  js: .taskfiles/js.yaml
  prettier: .taskfiles/prettier.yaml
  gen: .taskfiles/gen.yaml

tasks:
  default:
    silent: true
    cmds:
      - task -l

  run:
    desc: Runs backend and frontend in dev mode
    cmds:
      - npx concurrently "task go:run" "task js:run"

  deps:
    desc: Install dependencies
    deps:
      - js:deps
      - go:deps

  build:
    desc: Builds a production executable
    deps:
      - js:build
    cmds:
      - task go:build

  test:
    desc: Runs all test targets
    deps:
      - go:test
      - js:test

  gen:
    desc: Runs all codegen targets
    deps:
      - task: gen:sqlc
      - task: gen:proto

  format:
    desc: Runs all format writer targets
    deps:
      - task: go:format
      - task: prettier:format

  format-check:
    desc: Runs all format checker targets
    deps:
      - task: go:format
      - task: prettier:check

  lint-check:
    desc: Runs all lint checker targets
    deps:
      - task: js:lint-check

  ci:
    desc: Everything we need for ci to pass
    deps:
      - task: test
      - task: format-check
      - task: lint-check
      - task: gen:check
