version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  run:
    desc: Runs backend and frontend in dev mode
    cmds:
      - npx concurrently "task run-go" "task run-js"

  run-go:
    desc: Runs backend in dev mode
    cmds:
      - go run .

  run-js:
    desc: Runs frontend in dev mode
    env:
      VITE_JOT_PRODUCTION: false
    cmds:
      - npm run dev

  build:
    desc: Builds a production executable
    deps:
      - build-js
    cmds:
      - task build-go

  build-js:
    desc: Builds client app
    env:
      VITE_JOT_PRODUCTION: true
      NODE_ENV: production
    cmds:
      - npm run build

  build-go:
    desc: Builds just the go binary without the client
    env:
      CGO_ENABLED: true
    cmds:
      - go build -o ./build/jot -tags production .

  gen:
    desc: Runs all codegen targets
    deps:
      - task: gen-sqlc
      - task: gen-proto

  gen-sqlc:
    desc: Generates db code
    deps:
      - task: fix-prettier-sql
    cmds:
      - rm -rf ./internal/generated/db
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc generate

  gen-proto:
    desc: Generates proto code
    cmds:
      - rm -rf ./internal/generated/proto
      - rm -rf ./client/generated/proto
      - npx buf generate

  format:
    desc: Runs all format targets
    deps:
      - task: format-go
      - task: format-prettier

  format-go:
    desc: Formats all go code
    cmds:
      - go fmt .

  format-prettier:
    desc: Formats code with prettier
    cmds:
      - npx prettier --log-level error --write .
      - task fix-prettier-sql

  fix-prettier-sql:
    desc: fixes prettier's incompatibility with sqlc
    cmds:
      # prettier's sql formatting breaks sqlc because prettier wants to put spaces between a
      # word and an open paren, like this: `where (...)`. this is problematic for sqlc named
      # args because they're formatted as `sqlc.arg(...)`, which results in prettier outputting
      # `sqlc.arg (...)`. this causes sqlc to blow up because of the space between arg and (
      - find . -type f -name "*.sql" -exec sed -i'' -E 's/(sqlc\.[[:alnum:]]+) \(/\1(/g' {} \;
