name: build-and-push-binaries
runs-on: ubuntu-latest
inputs:
  github_token:
    description: 'token to publish'
    require: true
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.12.0
    - run: go install github.com/go-task/task/v3/cmd/task@latest
    - run: task deps
    - run: task build-js
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: nightly
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
