name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build docker image
        uses: ./.github/actions/build-docker
        with:
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
